# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_recombination_cpp <- function(geno_df, tol = 1e-5, max_iter = 1000L, r_init = NULL) {
    .Call(`_selfmap_estimate_recombination_cpp`, geno_df, tol, max_iter, r_init)
}

forward_backward_cpp <- function(geno, t, r) {
    .Call(`_selfmap_forward_backward_cpp`, geno, t, r)
}

#' A no-op function just to give the package something to compile.
#' @export
placeholder_cpp <- function() {
    invisible(.Call(`_selfmap_placeholder_cpp`))
}

