# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A no-op function just to give the package something to compile.
#' @export
placeholder_cpp <- function() {
    invisible(.Call(`_selfmap_placeholder_cpp`))
}

